name: Deploy

on:
  workflow_run:
    workflows: ["Sync changes to Superblocks"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy
        uses: superblocksteam/deploy-action@v1
        id: deploy
        with:
          token: ${{ secrets.SUPERBLOCKS_TOKEN }}
          domain: staging.superblocks.com
